# 工作流的名称
name: 自动注册脚本

# 工作流的触发条件
on:
  # 1. 定时触发：使用 Cron 表达式
  # 下面的表达式 '0 */6 * * *' 表示每 6 小时运行一次
  # 如果想修改时间，可以访问 https://crontab.guru/ 来生成表达式
  schedule:
    - cron: '* * * * *'

  # 2. 手动触发：允许你在 GitHub Actions 页面点击按钮来运行
  workflow_dispatch:

# 定义需要执行的任务
jobs:
  run-registration-task:
    # 指定运行环境，使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest

    # 定义任务中的步骤
    steps:
      # 第一步：检出代码
      # 这个步骤会将你的仓库代码下载到运行环境中
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      # 指定使用 Node.js 的版本，这里用 18.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # cache: 'npm' # 缓存npm依赖，加快后续运行速度

      # 第三步：安装脚本依赖
      # 因为我们的脚本用到了 axios，所以需要先安装它
      - name: Install dependencies
        run: npm install axios

      # 第四步：运行注册脚本
      - name: Run the registration script
        run: node register.js
